#!/usr/bin/env python3
import os
import re
import sys
from pathlib import Path

from bmad_sync_lib import (
    build_issue_body,
    create_issue,
    ensure_label_exists,
    format_timestamp,
    is_step_04_completed,
    link_sub_issue,
    load_mapping,
    parse_frontmatter,
    save_mapping,
)

LABEL_NAME = "bmad"


def parse_epics_md(content: str) -> list[dict]:
    epics = []
    current_epic = None

    lines = content.split("\n")
    epic_pattern = re.compile(r"^#+\s*Epic\s+(\d+)[\s:–-]*(.+)", re.IGNORECASE)
    story_pattern = re.compile(r"^#+\s*\d+\.\d+\s+(.+)")

    for line in lines:
        epic_match = epic_pattern.match(line)
        if epic_match:
            if current_epic:
                epics.append(current_epic)
            epic_num = epic_match.group(1)
            epic_title = epic_match.group(2).strip()
            current_epic = {
                "key": epic_num,
                "title": epic_title,
                "stories": [],
            }
            continue

        if current_epic:
            story_match = story_pattern.match(line)
            if story_match:
                story_title = story_match.group(1).strip()
                current_epic["stories"].append({
                    "title": story_title,
                })

    if current_epic:
        epics.append(current_epic)

    return epics


def process_epics_new(repo: str, token: str, mapping: dict, content: str) -> dict:
    if not is_step_04_completed(content):
        print("Skipping epics creation: step-04-final-validation not completed")
        return mapping

    epics = parse_epics_md(content)
    ensure_label_exists(repo, token)

    for epic in epics:
        epic_key = epic["key"]
        if epic_key in mapping["epics"]:
            continue

        epic_body = build_issue_body(content)

        epic_title_str = f"Epic {epic_key}: {epic['title']}"
        issue_id, issue_number = create_issue(repo, token, epic_title_str, epic_body, [LABEL_NAME])

        mapping["epics"][epic_key] = {
            "issue_id": issue_id,
            "issue_number": issue_number,
            "title": epic["title"],
        }

        print(f"Created epic issue #{issue_number}: {epic_title_str}")

        for story in epic["stories"]:
            story_body = f"""## Story: {story['title']}

Generated by BMad sync workflow.
"""
            story_issue_id, story_issue_number = create_issue(
                repo, token, story["title"], story_body, [LABEL_NAME]
            )

            story_key = f"{epic_key}-{story['title']}"
            mapping["stories"][story_key] = {
                "issue_id": story_issue_id,
                "issue_number": story_issue_number,
                "parent_epic": epic_key,
            }

            link_sub_issue(repo, token, issue_number, story_issue_id)
            print(f"  Created story sub-issue #{story_issue_number}: {story['title']}")

    return mapping


def process_epics_modified(repo: str, token: str, mapping: dict, content: str) -> dict:
    from bmad_sync_lib import add_comment, get_file_commit_sha

    epics = parse_epics_md(content)
    repo_env = os.environ.get("GITHUB_REPOSITORY", "")

    for epic in epics:
        epic_key = epic["key"]
        if epic_key not in mapping["epics"]:
            continue

        issue_number = mapping["epics"][epic_key]["issue_number"]
        commit_sha = get_file_commit_sha("_bmad-output/planning-artifacts/epics.md")
        commit_url = f"https://github.com/{repo_env}/commit/{commit_sha}" if commit_sha else None

        timestamp = format_timestamp()
        if commit_url:
            comment = f"""**BMad Sync Update** - {timestamp}

Epics file has been modified. Review the changes.

Commit: [{commit_sha}]({commit_url})
"""
        else:
            comment = f"""**BMad Sync Update** - {timestamp}

Epics file has been modified. Manual review may be needed.
"""
        add_comment(repo, token, issue_number, comment)

    return mapping


def main():
    repo = os.environ.get("GITHUB_REPOSITORY")
    token = os.environ.get("GITHUB_TOKEN")
    sync_all = os.environ.get("SYNC_ALL", "false").lower() == "true"

    if not repo or not token:
        print("ERROR: GITHUB_REPOSITORY and GITHUB_TOKEN must be set")
        sys.exit(1)

    mapping = load_mapping()

    file_path = "_bmad-output/planning-artifacts/epics.md"
    if not os.path.exists(file_path):
        print(f"ERROR: {file_path} not found")
        sys.exit(1)

    content = Path(file_path).read_text()

    if sync_all:
        new_files = [file_path]
        modified_files = []
    else:
        new_files = [file_path]
        modified_files = []

    for f in new_files:
        if "planning-artifacts/epics.md" in f:
            mapping = process_epics_new(repo, token, mapping, content)

    for f in modified_files:
        if "planning-artifacts/epics.md" in f:
            mapping = process_epics_modified(repo, token, mapping, content)

    save_mapping(mapping)
    print(f"Epics sync completed.")


if __name__ == "__main__":
    main()