//go:build harness

package harness

import (
	"fmt"
	"math"
	"os/exec"
	"runtime"
	"strings"
	"time"
)

// renderReport formats every measurement as the Markdown written to
// bench-results/harness.md. README and docs/benchmark-results.md numbers
// are copied from this output only.
func renderReport(cat *Catalog, tr tokenResults, lr latencyResults, sc []check, asserts []assertion, elapsed time.Duration) string {
	var b strings.Builder
	w := func(format string, args ...interface{}) { fmt.Fprintf(&b, format, args...) }

	w("# LeanProxy harness results\n\n")
	w("Generated by `make harness` (tests/harness, issue #301): the real `leanproxy-mcp server run --stdio` binary, driven over pipes, in front of %d catalog MCP servers (%d tools).\n\n", len(cat.Servers), cat.ToolCount())
	w("| Field | Value |\n|---|---|\n")
	w("| Commit | `%s` |\n", gitCommit())
	w("| Date (UTC) | %s |\n", time.Now().UTC().Format("2006-01-02 15:04"))
	w("| Host | %s/%s, %d CPUs, %s |\n", runtime.GOOS, runtime.GOARCH, runtime.NumCPU(), runtime.Version())
	w("| Harness wall time (incl. build) | %.1f s |\n", elapsed.Seconds())
	w("| Token unit | `pkg/reporter.Estimator`: 1 token ≈ 4 chars of the full JSON-RPC response line |\n\n")

	w("## Assertions\n\n| Assertion | Measured | Result |\n|---|---|---|\n")
	for _, a := range asserts {
		w("| %s | %s | %s |\n", a.name, a.measured, passFail(a.pass))
	}

	w("\n## Tokens: discovery payloads\n\n| Payload | Tokens |\n|---|---:|\n")
	w("| LeanProxy `tools/list` (router, 4 tools) | %d |\n", tr.router)
	w("| LeanProxy `list_servers` (%d servers) | %d |\n", len(cat.Servers), tr.listServers)
	sr := tr.search
	w("| LeanProxy `search_tools` (k=5), per lookup: average / max over %d labeled intents | %.0f / %d |\n", sr.lookups, sr.avgTokens, sr.maxTokens)
	w("| LeanProxy `list_tools(server)` for the same intents' servers, per lookup: average | %.0f |\n", sr.avgListTools)
	w("| `invoke_tool` request overhead vs a native `tools/call` | +%d |\n", tr.invokeRequest-tr.directRequest)
	w("| `invoke_tool` response overhead vs a native `tools/call` | %+d |\n", tr.invokeResponse-tr.directResponse)

	w("\n## `search_tools` ranking through the binary\n\n")
	w("The %d labeled intents of `pkg/toolsearch/testdata/intents.json` (44 from the audit, the rest written independently of the catalog descriptions), each sent as one `search_tools` call (BM25, default config).\n\n", sr.lookups)
	w("| Measurement | Value |\n|---|---:|\n")
	w("| Recall@1 (right tool first) | %s |\n", ratio(sr.at1, sr.lookups))
	w("| Recall@5 (right tool in the answer) | %s |\n", ratio(sr.at5, sr.lookups))
	w("| Tokens per lookup vs `list_tools(server)` | %s |\n", pct(int(math.Round(sr.avgTokens)), int(math.Round(sr.avgListTools))))

	w("\n## Tokens: per server\n\n| Server | Tools | Native `tools/list` | LeanProxy `list_tools(server)` | LeanProxy router | Router vs native |\n|---|---:|---:|---:|---:|---:|\n")
	var nativeSum, listSum int
	for _, s := range cat.Servers {
		n, l := tr.native[s.Name], tr.listTools[s.Name]
		nativeSum += n
		listSum += l
		w("| %s | %d | %d | %d | %d | %s |\n", s.Name, tr.toolCounts[s.Name], n, l, tr.router, pct(tr.router, n))
	}
	w("| **all %d** | **%d** | **%d** | **%d** | **%d** | **%s** |\n", len(cat.Servers), cat.ToolCount(), nativeSum, listSum, tr.router, pct(tr.router, nativeSum))

	w("\n## Tokens: session replay\n\n")
	w("Native = all %d servers' `tools/list` in context every turn (turn 1 at 1×, later turns at 0.25× cache read). ", len(cat.Servers))
	w("LeanProxy = router + every discovery output already in context (turn 1 at 1×, later turns at 0.25×) + that turn's new discovery output at 1×. ")
	w("With `list_tools`, discovery is `list_servers` on turn 1 and `list_tools` on a server's first use; with `search_tools`, it is one `search_tools(query)` the first time a tool is needed (a miss outside the top 5 also pays a `list_tools` fallback and one more turn). ")
	w("Tool results are identical on every path and excluded. Extra turns = discovery round-trips LeanProxy adds; their cost is not included in the token columns.\n\n")
	w("| Session | Prompts | Servers used | Native tokens | LeanProxy `list_tools` tokens | Savings | Extra LLM turns | LeanProxy `search_tools` tokens | Savings | Extra LLM turns | Search misses |\n|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n")
	for _, s := range tr.sessionResults {
		w("| %s | %d | %d | %d | %d | %s | +%d | %d | %s | +%d | %d |\n", s.name, s.prompts, s.servers, s.native, s.lean, pct(s.lean, s.native), s.extraTurns, s.searchLean, pct(s.searchLean, s.native), s.searchExtraTurns, s.searchMisses)
	}

	w("\n## Latency and throughput\n\n| Measurement | Value |\n|---|---:|\n")
	w("| Paced sequential `invoke_tool`, %d unique calls: p50 / p95 / p99 via proxy | %.2f / %.2f / %.2f ms |\n", len(lr.proxyMS), percentile(lr.proxyMS, 0.5), percentile(lr.proxyMS, 0.95), percentile(lr.proxyMS, 0.99))
	w("| Same calls direct to the mock: p50 / p95 / p99 | %.2f / %.2f / %.2f ms |\n", percentile(lr.directMS, 0.5), percentile(lr.directMS, 0.95), percentile(lr.directMS, 0.99))
	w("| Proxy overhead (proxy − direct): p50 / p95 / p99 | %.2f / %.2f / %.2f ms |\n",
		percentile(lr.proxyMS, 0.5)-percentile(lr.directMS, 0.5), percentile(lr.proxyMS, 0.95)-percentile(lr.directMS, 0.95), percentile(lr.proxyMS, 0.99)-percentile(lr.directMS, 0.99))
	rps := 0.0
	if lr.burstWall > 0 {
		rps = float64(burstCalls) / lr.burstWall.Seconds()
	}
	w("| %d-call pipelined burst over 5 servers: wall / throughput / errors | %d ms / %.0f req/s / %d |\n", burstCalls, lr.burstWall.Milliseconds(), rps, lr.burstErrors)
	w("| %d parallel calls to a %d ms tool on one server (default `max_in_flight` 32 per server, so two waves): wall | %d ms |\n", parallelCalls, parallelDelayMS, lr.parallelWall.Milliseconds())
	w("| 5 MB tool response: via proxy / direct | %d ms / %d ms |\n", lr.bigProxy.Milliseconds(), lr.bigDirect.Milliseconds())
	w("| Streamable HTTP front end (`server run --http`), same paced calls: p50 / p95 / p99 | %.2f / %.2f / %.2f ms |\n", percentile(lr.http.ms, 0.5), percentile(lr.http.ms, 0.95), percentile(lr.http.ms, 0.99))
	w("| Streamable HTTP overhead (HTTP − direct): p50 / p95 | %.2f / %.2f ms |\n", percentile(lr.http.ms, 0.5)-percentile(lr.directMS, 0.5), percentile(lr.http.ms, 0.95)-percentile(lr.directMS, 0.95))
	hrps := 0.0
	if lr.http.burstWall > 0 {
		hrps = float64(httpBurstCalls) / lr.http.burstWall.Seconds()
	}
	w("| %d-call Streamable HTTP burst, %d concurrent clients, over 5 servers: wall / throughput / errors | %d ms / %.0f req/s / %d |\n", httpBurstCalls, httpBurstWorkers, lr.http.burstWall.Milliseconds(), hrps, lr.http.burstErrors)
	w("| Proxy RSS: idle (5 servers warm) / after the burst | %s / %s |\n", rss(lr.rssIdleKB), rss(lr.rssBurstKB))
	w("| Binary size (%s/%s, `-trimpath -ldflags=\"-s -w\"`) | %.1f MiB |\n", runtime.GOOS, runtime.GOARCH, float64(lr.binaryBytes)/(1<<20))

	w("\n## Safety (Token Firewall, default redaction + injection guard enabled)\n\n| Check | Detail | Result |\n|---|---|---|\n")
	for _, c := range sc {
		w("| %s | %s | %s |\n", c.name, c.detail, passFail(c.pass))
	}
	return b.String()
}

func passFail(ok bool) string {
	if ok {
		return "PASS"
	}
	return "**FAIL**"
}

// pct is the saving of lean over native, e.g. "-73.1%".
func pct(lean, native int) string {
	if native == 0 {
		return "n/a"
	}
	saving := 100 * (1 - float64(lean)/float64(native))
	if saving < 0 {
		return fmt.Sprintf("+%.1f%% (more tokens)", -saving)
	}
	return fmt.Sprintf("−%.1f%%", saving)
}

// ratio renders n/d as "n/d (x.y%)".
func ratio(n, d int) string {
	if d == 0 {
		return "n/a"
	}
	return fmt.Sprintf("%d/%d (%.1f%%)", n, d, 100*float64(n)/float64(d))
}

func rss(kb int) string {
	if kb < 0 {
		return "n/a (no /proc)"
	}
	return fmt.Sprintf("%.1f MiB", float64(kb)/1024)
}

func gitCommit() string {
	out, err := exec.Command("git", "rev-parse", "--short", "HEAD").Output()
	if err != nil {
		return "unknown"
	}
	return strings.TrimSpace(string(out))
}
